### ISSUE TITLE
egate.php

### ISSUE THREAD

**Issue by uno2xx** [PHPieces/anz-egate#2]
Great package but I have one issue. egate.php not found under config.

Thanks,
Bryan

**Comment by jlyons-bgl** [comment]
whoops, looks like when you use 'create' on the gateway it looks for the config 'egate.url'. when it can't find it, it tries to load it from the files I used in testing. I'll do release to fix it but as a workaround you can run
`Config::set('egate', ['url' => 'https://migs.mastercard.com.au/vpcdps'])`
before trying to call the create method on the Gateway.

**Comment by jclyons52** [comment]
@uno2xx I've pushed version 0.2.0 which no longer uses the Config class. it has a default url set for the egate which can be configured. can you confirm this resolves the issue?

**Comment by uno2xx** [comment]
@jclyons52 yes it's working now. Thank you :)
